### ISSUE TITLE
Luminance channel

### ISSUE THREAD

**Issue by VitalSkib** [safina3d/c4d-random-color#1]
Hey. 
Is it possible to change the code somehow, so that it creates a new material, enable the Luminance channel and apply color there, at the same time turning off the Reflectance and Color channels? 
If so, how can this be done? 
Thank you.

**Comment by safina3d** [comment]
Hello,
Thank you for your comment ;) I added an options dialog. Now you can choose which channels you want to activate and apply or not the random color.
https://safina3d.blogspot.com/p/randomcolor.html

**Comment by VitalSkib** [comment]
Hey. Thanks for the quick response and adding channel selection. :)
Good luck!
