### ISSUE TITLE
R23 compatibility and few issues

### ISSUE THREAD

**Issue by VitalSkib** [safina3d/c4d-random-color#2]
This was posted by me on your site, but in the wrong place. 
This comment is for the Random Color plugin.
_"Hey.
May I ask you to add compatibility with Cinema 4D R23, please?
And if you don't mind, then a couple of comments that need to be added or fixed.
First, the script completely ignores child objects if they are present and is executed only for the parent object.
And second, for some reason it breaks the UV, despite the fact that it already exists and simply adds a second UV set.
Perhaps this is done by Cinema 4D itself, but then it would be good to add this in the code: if UV is present, then do not change or add anything.
I don't know how to do this, but..
Thanks in advance."_

**Comment by safina3d** [comment]
> May I ask you to add compatibility with Cinema 4D R23, please?
:point_right: Done.

> First, the script completely ignores child objects if they are present and is executed only for the parent object.
:point_right: Done.

> And second, for some reason it breaks the UV, despite the fact that it already exists and simply adds a second UV set.
I can't reproduce this one :dizzy_face: It's very odd because the plugin doesn't deal with UVs in any way..

**Comment by VitalSkib** [comment]
Wow, so fast! 
Thank you very much! 
As for the last point is perhaps Cinema 4D does something wrong then. 
I need to test this and try to figure out what's going on. 
I will write if there are any questions or ideas.
